import { Injectable, inject } from '@angular/core';
import { ProductCatalogService } from './product-catalog.service';
import { CashflowService } from './cashflow.service';
import { CatalogService } from './catalog.service';
import { Quote } from '../models/catalog.model';
import { Transaction } from '../models/cashflow.model';
import { DataSyncService } from './data-sync.service';

@Injectable({
  providedIn: 'root',
})
export class BusinessAutomationService {
  private productService = inject(ProductCatalogService);
  private cashflowService = inject(CashflowService);
  private catalogService = inject(CatalogService);
  private dataSyncService = inject(DataSyncService);

  /**
   * Confirma la venta de una cotización:
   * 1. Cambia el estado de la cotización a 'sold'.
   * 2. Registra un ingreso en flujo de caja por el total de la cotización.
   * 3. Para cada producto en la cotización que tenga "trackInventory" activo, descuenta el stock.
   */
  confirmQuoteSale(quoteId: string): boolean {
    const quotes = this.catalogService.quotes();
    const quoteIndex = quotes.findIndex((q: Quote) => q.id === quoteId);
    if (quoteIndex === -1) return false;

    const quote = quotes[quoteIndex];
    if (quote.status === 'sold') return false; // Ya vendida

    // Generar la transacción de ingreso en Flujo de Caja
    const total = this.catalogService.getQuoteTotal(quote);
    const txId = crypto.randomUUID();
    const transaction: Transaction = {
      id: txId,
      type: 'ingreso',
      category: 'ventas',
      description: `Venta Cotización - Cliente: ${quote.clientName}`,
      amount: total,
      currency: 'COP', // TODO: read from quote.currency when available
      date: new Date().toISOString().split('T')[0],
      createdAt: new Date().toISOString(),
      notes: `Auto-generado por cotización vendida. Ref: ${quote.id}`,
      autoGenerated: true,
      sourceQuoteId: quoteId,
    };

    // Agregar transacción al servicio
    this.cashflowService.add(transaction);

    // Procesar descuento de inventario para los items enlazados
    for (const item of quote.items) {
      // Buscar el producto unificado por su id de catálogo (que coincide con product.id)
      const product = this.productService.getProductById(item.catalogId);
      if (product && product.trackInventory) {
        this.productService.registerMovement(
          product.id,
          'salida',
          item.quantity,
          `Venta Cotización - Cliente: ${quote.clientName}`,
          true,
          quoteId,
          txId
        );
      }
    }

    // Actualizar estado de la cotización
    this.catalogService.updateQuote(quoteId, {
      status: 'sold',
      soldAt: new Date().toISOString(),
      cashflowTransactionId: txId,
    });

    // Guardar inmediatamente en servidor
    this.dataSyncService.saveToServer();

    return true;
  }

  /**
   * Venta rápida directa de un producto (desde Inventario o Flujo de caja manual):
   * 1. Descuenta del inventario.
   * 2. Genera ingreso en flujo de caja.
   */
  registerProductSale(productId: string, qty: number, salePrice: number): boolean {
    const product = this.productService.getProductById(productId);
    if (!product) return false;

    const txId = crypto.randomUUID();
    const totalAmount = qty * salePrice;

    // 1. Registrar salida en Inventario
    if (product.trackInventory) {
      this.productService.registerMovement(
        productId,
        'salida',
        qty,
        'Venta rápida',
        true,
        undefined,
        txId
      );
    }

    // 2. Registrar Ingreso en Flujo de Caja
    const transaction: Transaction = {
      id: txId,
      type: 'ingreso',
      category: 'ventas',
      description: `Venta rápida: ${product.name} (x${qty})`,
      amount: totalAmount,
      currency: 'COP',
      date: new Date().toISOString().split('T')[0],
      createdAt: new Date().toISOString(),
      notes: `Venta de producto enlazada a inventario`,
      autoGenerated: true,
      linkedProductId: productId,
      linkedQuantity: qty,
    };
    this.cashflowService.add(transaction);

    // Guardar en servidor
    this.dataSyncService.saveToServer();
    return true;
  }

  /**
   * Compra / Abastecimiento directo de un producto:
   * 1. Aumenta stock en inventario.
   * 2. Registra egreso por compra de mercadería en flujo de caja.
   */
  registerProductPurchase(productId: string, qty: number, costPrice: number): boolean {
    const product = this.productService.getProductById(productId);
    if (!product) return false;

    const txId = crypto.randomUUID();
    const totalAmount = qty * costPrice;

    // 1. Registrar entrada en Inventario
    if (product.trackInventory) {
      this.productService.registerMovement(
        productId,
        'entrada',
        qty,
        'Compra / Reabastecimiento',
        true,
        undefined,
        txId
      );
    }

    // 2. Registrar Egreso en Flujo de Caja
    const transaction: Transaction = {
      id: txId,
      type: 'egreso',
      category: 'proveedores',
      description: `Compra / Reabastecimiento: ${product.name} (x${qty})`,
      amount: totalAmount,
      currency: 'COP',
      date: new Date().toISOString().split('T')[0],
      createdAt: new Date().toISOString(),
      notes: `Compra de producto enlazada a inventario`,
      autoGenerated: true,
      linkedProductId: productId,
      linkedQuantity: qty,
    };
    this.cashflowService.add(transaction);

    // Guardar en servidor
    this.dataSyncService.saveToServer();
    return true;
  }
}
