// ═══════════════════════════════════════════
// Producto Unificado — Modelos
// ═══════════════════════════════════════════

export interface Product {
  id: string;
  name: string;
  description: string;       // Descripción detallada para cotizaciones
  sku: string;               // Código/SKU único para inventario
  salePrice: number;         // Precio de venta al público (antes "price" en catálogo)
  costPrice: number;         // Costo unitario de adquisición (antes "costPerUnit" en inventario)
  unit: string;              // 'unidades', 'kg', 'litros', 'cajas', 'metros', 'rollos', 'paquetes', etc.
  category: string;
  currentStock: number;      // Stock actual físico disponible
  minStock: number;          // Umbral de alerta "Stock Crítico"
  active: boolean;           // Si está visible en el catálogo de ventas
  trackInventory: boolean;   // Si afecta o no el inventario al venderse
  createdAt: string;
}

export type MovementType = 'entrada' | 'salida';

export interface StockMovement {
  id: string;
  productId: string;
  productName: string;
  type: MovementType;
  quantity: number;
  reason: string;
  date: string;
  createdAt: string;
  autoGenerated?: boolean;   // Indica si el movimiento se creó de forma automática por un módulo externo
  sourceQuoteId?: string;    // Enlace a la cotización si es por venta
  sourceTransactionId?: string; // Enlace a flujo de caja
}
